(in-package :hexhammer)

;;; Offsets of x and y (low left origin) coordinates of hex (r = 0.5) vertices
(defmacro xofs (direction)
  (case direction
    (:E 1.0)
    (:NE 0.875)
    (:NNE 0.75)
    (:CEN '(xofs :N))
    (:N 0.5)
    (:NNW 0.25)
    (:NW 0.125)
    (:W 0.0)
    (:SW '(xofs :NW))
    (:SSW '(xofs :NNW))
    (:S '(xofs :N))
    (:SSE '(xofs :NNE))
    (:SE '(xofs :NE))))

(defmacro yofs (direction)
  (case direction
    (:E '(yofs :CEN))
    (:NE '(yofs :NW))
    (:NNE '(yofs :N))
    (:CEN (coerce (* 1/2 (sin (/ pi 3))) 'single-float))
    (:N (coerce (sin (/ pi 3)) 'single-float))
    (:NNW '(yofs :N))
    (:NW (coerce (* 3/4 (sin (/ pi 3))) 'single-float))
    (:W '(yofs :CEN))
    (:SW (coerce (* 1/4 (sin (/ pi 3))) 'single-float))
    (:SSW '(yofs :S))
    (:S 0.0)
    (:SSE '(yofs :S))
    (:SE '(yofs :SW))))

(defun unit-hex-crd (dir)
  (case dir
    (:CEN (crd 0.0 0.0))
    (:E (crd 1.0 0.0))
    (:NE (crd 0.75 (* +sin60+ 0.5)))
    (:NNE (crd 0.5 +sin60+))
    (:N (crd 0.0 +sin60+))
    (:NNW (crd -0.5 +sin60+))
    (:NW (crd -0.75 (* +sin60+ 0.5)))
    (:W (crd -1.0 0.0))
    (:SW (crd -0.75 (* +sin60+ -0.5)))
    (:SSW (crd -0.5 (- +sin60+)))
    (:S (crd 0.0 (- +sin60+)))
    (:SSE (crd 0.5 (- +sin60+)))
    (:SE (crd 0.75 (* +sin60+ -0.5)))))

(defun translate-unit-crd (crd r)
  (crd (* (x crd) r)
       (* -1 (y crd) r)))

(defun contour-offset (contour-index contour-count edge-vector-pix)
  "Returns contour's position on edge in pixels clockwise."
  (declare (fixnum contour-index contour-count)
	   (single-float edge-vector-pix))
  (let* ((margin (/ edge-vector-pix 4))
	 (width (/ (- edge-vector-pix
		      (* 2 margin))
		   (+ 1 (abs contour-count)))))
    (+ margin (* (1+ contour-index)
		 width))))
