(ql:quickload :serapeum)
(ql:quickload :sdl2)
(ql:quickload :cl-cairo2)
(ql:quickload :3d-vectors)

(with-compilation-unit ()
  (load "package.lisp")
  (load "util.lisp")
  (load "graphics.lisp")
  (load "map.lisp")
  (load "hex.lisp")
  (load "pgmread.lisp")
  (load "viewstate.lisp")
  (load "vectors.lisp")
  (load "shading.lisp")
  (load "contours.lisp")
  (load "window.lisp"))
